import::here('celldex',
    'BlueprintEncodeData',
    'HumanPrimaryCellAtlasData',
    'DatabaseImmuneCellExpressionData',
    'ImmGenData',
    'MonacoImmuneData',
    'MouseRNAseqData',
    'NovershternHematopoieticData',
    .character_only=TRUE
)
import::here('Seurat',
    'ScaleData', 'RunPCA', 'RunUMAP', 'FindNeighbors', 'FindClusters',
    .character_only=TRUE
)

## Objects
## celldex_switch

## Functions
## run_standard_clustering


celldex_switch=list2env(list(

    #259 RNA-seq samples of pure stroma and immune cells as generated and supplied by Blueprint and ENCODE
    'ENCODE'=BlueprintEncodeData,

    #713 microarray samples from the Human Primary Cell Atlas (HPCA) (Mabbott et al., 2013).
    'HPCA'=HumanPrimaryCellAtlasData,

    #1561 bulk RNA-seq samples of sorted immune cell populations
    'DICE'=DatabaseImmuneCellExpressionData,

    # 830 microarray samples of pure mouse immune cells, generated by the Immunologic Genome Project (ImmGen)
    'ImmGen'=ImmGenData,

    #114 bulk RNA-seq samples of sorted immune cell populations that can be found in GSE107011.
    'Monaco'=MonacoImmuneData,

    #358 bulk RNA-seq samples of sorted cell populations
    'MouseRNAseq'=MouseRNAseqData,

    #211 bulk human microarray samples of sorted hematopoietic cell populations that can be found in GSE24759
    'Hemato'=NovershternHematopoieticData
))


#' This is repeated across multiple analyses
#' See: https://satijalab.org/seurat/articles/integration_introduction.html#perform-an-integrated-analysis
#'
#' @export
run_standard_clustering <- function(seurat_obj, ndim=40) {
    seurat_obj <- ScaleData(seurat_obj, verbose = FALSE)
    seurat_obj <- RunPCA(seurat_obj, npcs = ndim, verbose = FALSE)
    seurat_obj <- RunUMAP(seurat_obj, reduction = "pca", dims = 1:ndim)
    seurat_obj <- FindNeighbors(seurat_obj, reduction = "pca", dims = 1:ndim)
    seurat_obj <- FindClusters(seurat_obj, resolution = 0.5)
    return(seurat_obj)
}
