import::here(celldex,
    'BlueprintEncodeData', 'HumanPrimaryCellAtlasData',
    'DatabaseImmuneCellExpressionData', 'ImmGenData',
    'MonacoImmuneData', 'MouseRNAseqData', 'NovershternHematopoieticData'
)
import::here(Seurat,
    'ScaleData', 'RunPCA', 'RunUMAP', 'FindNeighbors', 'FindClusters'
)
# import::here(SingleR, 'SingleR')

## Objects
## celldex_switch

## Functions
## run_standard_analysis_workflow


#' Celldex Switch
#' 
#' @description Choose a dataset: ENCODE, HPCA, DICE, Immgen, Monaco, MouseRNAseq, Hemato
#' 
celldex_switch=list2env(list(

    #259 RNA-seq samples of pure stroma and immune cells as generated and supplied by Blueprint and ENCODE
    'ENCODE'=BlueprintEncodeData,

    #713 microarray samples from the Human Primary Cell Atlas (HPCA) (Mabbott et al., 2013).
    'HPCA'=HumanPrimaryCellAtlasData,

    #1561 bulk RNA-seq samples of sorted immune cell populations
    'DICE'=DatabaseImmuneCellExpressionData,

    # 830 microarray samples of pure mouse immune cells, generated by the Immunologic Genome Project (ImmGen)
    'ImmGen'=ImmGenData,

    #114 bulk RNA-seq samples of sorted immune cell populations that can be found in GSE107011.
    'Monaco'=MonacoImmuneData,

    #358 bulk RNA-seq samples of sorted cell populations
    'MouseRNAseq'=MouseRNAseqData,

    #211 bulk human microarray samples of sorted hematopoietic cell populations that can be found in GSE24759
    'Hemato'=NovershternHematopoieticData
))


#' Standard Analysis Workflow
#'
#' @references
#' \href{https://satijalab.org/seurat/articles/integration_introduction.html#perform-an-integrated-analysis}{Seurat Documentation}
#' 
run_standard_analysis_workflow <- function(seurat_obj, ndim=40) {
    # seurat_obj <- NormalizeData(seurat_obj, verbose = FALSE)
    # seurat_obj <- FindVariableFeatures(seurat_obj, verbose = FALSE)
    seurat_obj <- ScaleData(seurat_obj, verbose = FALSE)
    seurat_obj <- RunPCA(seurat_obj, npcs = ndim, verbose = FALSE)
    seurat_obj <- FindNeighbors(seurat_obj, reduction = "pca", dims = 1:ndim)
    seurat_obj <- FindClusters(seurat_obj, resolution = 0.5)
    seurat_obj <- RunUMAP(seurat_obj, reduction = "pca", dims = 1:ndim)
    return(seurat_obj)
}
