## Adapted from: DIY_scRNAseq.R
## Assigns clusters and uses data from celldex to label them

wd = dirname(this.path::here())  # wd = '~/github/R/harrisonRTools'
reticulate::use_condaenv('r-reticulate')  # required for cellassign to access tensorflow through python
library('rjson')
library('cellassign')  # takes a few seconds
suppressMessages(library('Seurat'))
suppressMessages(library('DropletUtils'))
library('SingleR') # automated cell type annotation ('label transfer') using reference data
suppressMessages(library('celldex')) # a large collection of reference expression datasets with curated cell type labels for use with SingleR package
library('scran')
library('pheatmap')
# library('scater')  # plotUMAP, could not install this
library('ggplot2')
library('optparse')
library('logr')
source(file.path(wd, 'R', 'functions', 'file_io.R'))


# ----------------------------------------------------------------------
# Pre-script settings

# args
option_list = list(
    make_option(c("-i", "--input-file"),
                default='data/scrnaseq-ballesteros/integrated/spleen/integrated_seurat.RData',
                metavar='data/scrnaseq-ballesteros/integrated/spleen/integrated_seurat.RData',
                type="character",
                help="output of scrnaseq_integrated_analysis.R"),

    make_option(c("-o", "--output-dir"),
                default="figures/scrnaseq-ballesteros/integrated/spleen",
                metavar="figures/scrnaseq-ballesteros/integrated/spleen", type="character",
                help="set the output directory for the figures"),

    make_option(c("-c", "--celldex"),
                default='ImmGen', metavar='ImmGen', type="character",
                help="Choose from: ['ENCODE', 'HPCA', 'DICE', 'ImmGen', 'Monaco', 'MouseRNAseq', 'Hemato']"),

    make_option(c("-e", "--ensembl"),  default=FALSE,
                metavar="FALSE", action="store_true", type="logical",
                help="When querying celldex"),

    make_option(c("-t", "--troubleshooting"), default=FALSE, action="store_true",
                metavar="FALSE", type="logical",
                help="enable if troubleshooting to prevent overwriting your files")
)
opt_parser = OptionParser(option_list=option_list)
opt = parse_args(opt_parser)
dataset = basename(opt[['output-dir']])
troubleshooting = opt[['troubleshooting']]

# Start Log
start_time = Sys.time()
log <- log_open(paste0("covid19_scrnaseq_cluster_assignment-",
                       strftime(start_time, format="%Y%m%d_%H%M%S"), '.log'))
log_print(paste('Script started at:', start_time))

switch=list(

    #259 RNA-seq samples of pure stroma and immune cells as generated and supplied by Blueprint and ENCODE
    'ENCODE'=BlueprintEncodeData,

    #713 microarray samples from the Human Primary Cell Atlas (HPCA) (Mabbott et al., 2013).
    'HPCA'=HumanPrimaryCellAtlasData,

    #1561 bulk RNA-seq samples of sorted immune cell populations
    'DICE'=DatabaseImmuneCellExpressionData,

    # 830 microarray samples of pure mouse immune cells, generated by the Immunologic Genome Project (ImmGen)
    'ImmGen'=ImmGenData,

    #114 bulk RNA-seq samples of sorted immune cell populations that can be found in GSE107011.
    'Monaco'=MonacoImmuneData,

    #358 bulk RNA-seq samples of sorted cell populations
    'MouseRNAseq'=MouseRNAseqData,

    #211 bulk human microarray samples of sorted hematopoietic cell populations that can be found in GSE24759
    'Hemato'=NovershternHematopoieticData
)

# ----------------------------------------------------------------------
# Read Data

log_print(paste(Sys.time(), 'Reading data...'))

integrated_seurat <- load_rdata(file.path(wd, opt[['input-file']]))
sce_counts <- as.SingleCellExperiment(integrated_seurat)


# ----------------------------------------------------------------------
# Label clusters using celldex

get_data=switch[[opt$celldex]]
ref_data <- get_data(ensembl = opt[['ensembl']])  # ensembl=FALSE by default
predictions <- SingleR(
    test=sce_counts,
    assay.type.test=1,
    ref=ref_data,
    labels=ref_data[['label.main']]
)
plotScoreHeatmap(predictions)  # SingleR

# now add back to singleCellExperiment object (or Seurat objects)
sce_counts[["SingleR.labels"]] <- predictions[['labels']]


# ----------------------------------------------------------------------
# Plot results

seurat_counts <- as.Seurat(sce_counts, counts = NULL)
DimPlot(
    seurat_counts, reduction = "UMAP", 
    split.by = "treatment", # this facets the plot 
    group.by = "SingleR.labels", # labels the cells with values from your group.by variable
    label = TRUE
)
if (!troubleshooting) {
    ggsave(file.path(wd, opt[['output-dir']],
                     paste0('umap-', dataset, '-integrated-', tolower(opt$celldex), '_labeled.png')),
           height=750, width=1200, dpi=300, units="px", scaling=0.5)
}


end_time = Sys.time()
log_print(paste('Script ended at:', Sys.time()))
log_print(paste("Script completed in:", difftime(end_time, start_time)))
log_close()
